// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDsG58d6WJluANun7vVWu9-Ofwgqkc4T4',
    appId: '1:738783354110:web:af90b36ae4b9aca0e7d9af',
    messagingSenderId: '738783354110',
    projectId: 'drawper',
    authDomain: 'drawper.firebaseapp.com',
    storageBucket: 'drawper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1YBBJRWu10e37aQQwsAsgtCXwhdVCfrY',
    appId: '1:738783354110:android:73bef40a4ff53967e7d9af',
    messagingSenderId: '738783354110',
    projectId: 'drawper',
    storageBucket: 'drawper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApz5TB6eF32C77K5sMCetNdBa6A5lFW2k',
    appId: '1:738783354110:ios:dfd5213ad1547ac6e7d9af',
    messagingSenderId: '738783354110',
    projectId: 'drawper',
    storageBucket: 'drawper.appspot.com',
    iosBundleId: 'com.example.drawper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApz5TB6eF32C77K5sMCetNdBa6A5lFW2k',
    appId: '1:738783354110:ios:0fb694912576b7cae7d9af',
    messagingSenderId: '738783354110',
    projectId: 'drawper',
    storageBucket: 'drawper.appspot.com',
    iosBundleId: 'com.example.drawper.RunnerTests',
  );
}
